# Generated by Django 5.2.15 on 2026-06-19 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_code', models.CharField(db_index=True, help_text='Unique base62 short identifier.', max_length=20, unique=True)),
                ('original_url', models.URLField(help_text='The destination URL.', max_length=2048)),
                ('click_count', models.PositiveIntegerField(default=0, help_text='Cache fallback click count counter.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['short_code'], name='urls_app_sh_short_c_b5966e_idx'), models.Index(fields=['created_at'], name='urls_app_sh_created_cc9592_idx')],
            },
        ),
    ]
