# Generated by Django 5.2.15 on 2026-06-19 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('urls_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClickEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, help_text='IP address of the visitor.', null=True)),
                ('country', models.CharField(db_index=True, default='Unknown', help_text="Country resolved from the visitor's IP address.", max_length=100)),
                ('browser', models.CharField(db_index=True, default='Unknown', help_text="Browser name resolved from the visitor's User-Agent.", max_length=100)),
                ('operating_system', models.CharField(db_index=True, default='Unknown', help_text="Operating system resolved from the visitor's User-Agent.", max_length=100)),
                ('referrer', models.TextField(blank=True, help_text='HTTP Referer header.', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Raw HTTP User-Agent header.', null=True)),
                ('clicked_at', models.DateTimeField(db_index=True, help_text='Exact timestamp of the redirection.')),
                ('short_url', models.ForeignKey(help_text='The associated shortened URL.', on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='urls_app.shorturl')),
            ],
            options={
                'ordering': ['-clicked_at'],
                'indexes': [models.Index(fields=['clicked_at'], name='analytics_a_clicked_4261d7_idx'), models.Index(fields=['short_url', 'clicked_at'], name='analytics_a_short_u_9d2191_idx'), models.Index(fields=['country'], name='analytics_a_country_13df5f_idx'), models.Index(fields=['browser'], name='analytics_a_browser_1e7891_idx'), models.Index(fields=['operating_system'], name='analytics_a_operati_f7bf63_idx')],
            },
        ),
    ]
